services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lapsusgateway
      MYSQL_DATABASE: AgriculturaDB
      MYSQL_USER: Admin
      MYSQL_PASSWORD: lapsusgateway
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Montaje del archivo de inicialización

volumes:
  db_data: